services:  
  agent_service:  
    build:  
      context: .  
      dockerfile: Dockerfile.agent_service  
    environment:  
      - PORT=8000  
    ports:  
      - "8000:8000" 
    env_file:
      - secrets.env 
  streamlit_app:  
    build:  
      context: .  
      dockerfile: Dockerfile.streamlit_app  
    environment:  
      - AGENT_SERVICE_URL=http://agent_service:8000  
    ports:  
      - "8501:8501"  
    depends_on:  
      - agent_service  
