name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository == 'james-tn/multi-modal-rag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TARGET_REPO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Mirror repository
        run: |
          ls -lisa
          git remote add target git@github.com:trimble-transport/ttc-rainbows-end-customer-care-agent-service.git
          git fetch --all
          GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push --mirror --force target